name: Add Topic Name
on:
  push:
    branches: [main] # Change this to the branch name you want to use
  pull_request:
    branches: [main] # Change this to the branch name you want to use

jobs:
  add_topic_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add topic name
      run: |
        filename=$(basename $GITHUB_EVENT_PATH .json)
        topic=${filename%.*}
        echo "Adding topic $topic to repository"
        curl -X PUT \
          -H "Authorization: token ${{ secrets.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 }}" \
          -H "Accept: application/vnd.github.mercy-preview+json" \
          "https://api.github.com/repos/${{ github.repository }}/topics" \
          -d "{\"names\": [\"$topic\"]}"

